// Code generated by MockGen. DO NOT EDIT.
// Source: ./repository.go

// Package mock_repository is a generated GoMock package.
package mock_repository

import (
	models "homework-3/internal/pkg/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDatabaseRepo is a mock of DatabaseRepo interface.
type MockDatabaseRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseRepoMockRecorder
}

// MockDatabaseRepoMockRecorder is the mock recorder for MockDatabaseRepo.
type MockDatabaseRepoMockRecorder struct {
	mock *MockDatabaseRepo
}

// NewMockDatabaseRepo creates a new mock instance.
func NewMockDatabaseRepo(ctrl *gomock.Controller) *MockDatabaseRepo {
	mock := &MockDatabaseRepo{ctrl: ctrl}
	mock.recorder = &MockDatabaseRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabaseRepo) EXPECT() *MockDatabaseRepoMockRecorder {
	return m.recorder
}

// DeleteReservationByID mocks base method.
func (m *MockDatabaseRepo) DeleteReservationByID(id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReservationByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReservationByID indicates an expected call of DeleteReservationByID.
func (mr *MockDatabaseRepoMockRecorder) DeleteReservationByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReservationByID", reflect.TypeOf((*MockDatabaseRepo)(nil).DeleteReservationByID), id)
}

// DeleteReservationsByRoomID mocks base method.
func (m *MockDatabaseRepo) DeleteReservationsByRoomID(roomId int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReservationsByRoomID", roomId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReservationsByRoomID indicates an expected call of DeleteReservationsByRoomID.
func (mr *MockDatabaseRepoMockRecorder) DeleteReservationsByRoomID(roomId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReservationsByRoomID", reflect.TypeOf((*MockDatabaseRepo)(nil).DeleteReservationsByRoomID), roomId)
}

// DeleteRoomByID mocks base method.
func (m *MockDatabaseRepo) DeleteRoomByID(id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoomByID", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoomByID indicates an expected call of DeleteRoomByID.
func (mr *MockDatabaseRepoMockRecorder) DeleteRoomByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoomByID", reflect.TypeOf((*MockDatabaseRepo)(nil).DeleteRoomByID), id)
}

// GetReservationByID mocks base method.
func (m *MockDatabaseRepo) GetReservationByID(id int64) (*models.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReservationByID", id)
	ret0, _ := ret[0].(*models.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReservationByID indicates an expected call of GetReservationByID.
func (mr *MockDatabaseRepoMockRecorder) GetReservationByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReservationByID", reflect.TypeOf((*MockDatabaseRepo)(nil).GetReservationByID), id)
}

// GetReservationsByRoomID mocks base method.
func (m *MockDatabaseRepo) GetReservationsByRoomID(roomID int64) ([]*models.Reservation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReservationsByRoomID", roomID)
	ret0, _ := ret[0].([]*models.Reservation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReservationsByRoomID indicates an expected call of GetReservationsByRoomID.
func (mr *MockDatabaseRepoMockRecorder) GetReservationsByRoomID(roomID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReservationsByRoomID", reflect.TypeOf((*MockDatabaseRepo)(nil).GetReservationsByRoomID), roomID)
}

// GetRoomByID mocks base method.
func (m *MockDatabaseRepo) GetRoomByID(id int64) (*models.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomByID", id)
	ret0, _ := ret[0].(*models.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomByID indicates an expected call of GetRoomByID.
func (mr *MockDatabaseRepoMockRecorder) GetRoomByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomByID", reflect.TypeOf((*MockDatabaseRepo)(nil).GetRoomByID), id)
}

// GetRoomByName mocks base method.
func (m *MockDatabaseRepo) GetRoomByName(name string) (*models.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomByName", name)
	ret0, _ := ret[0].(*models.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomByName indicates an expected call of GetRoomByName.
func (mr *MockDatabaseRepoMockRecorder) GetRoomByName(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomByName", reflect.TypeOf((*MockDatabaseRepo)(nil).GetRoomByName), name)
}

// InsertReservation mocks base method.
func (m *MockDatabaseRepo) InsertReservation(reservation *models.Reservation) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertReservation", reservation)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertReservation indicates an expected call of InsertReservation.
func (mr *MockDatabaseRepoMockRecorder) InsertReservation(reservation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertReservation", reflect.TypeOf((*MockDatabaseRepo)(nil).InsertReservation), reservation)
}

// InsertRoom mocks base method.
func (m *MockDatabaseRepo) InsertRoom(room *models.Room) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertRoom", room)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertRoom indicates an expected call of InsertRoom.
func (mr *MockDatabaseRepoMockRecorder) InsertRoom(room interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertRoom", reflect.TypeOf((*MockDatabaseRepo)(nil).InsertRoom), room)
}

// UpdateReservation mocks base method.
func (m *MockDatabaseRepo) UpdateReservation(res *models.Reservation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReservation", res)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReservation indicates an expected call of UpdateReservation.
func (mr *MockDatabaseRepoMockRecorder) UpdateReservation(res interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReservation", reflect.TypeOf((*MockDatabaseRepo)(nil).UpdateReservation), res)
}

// UpdateRoom mocks base method.
func (m *MockDatabaseRepo) UpdateRoom(room *models.Room) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoom", room)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRoom indicates an expected call of UpdateRoom.
func (mr *MockDatabaseRepoMockRecorder) UpdateRoom(room interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoom", reflect.TypeOf((*MockDatabaseRepo)(nil).UpdateRoom), room)
}
